# Generated by Django 5.0.6 on 2026-08-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_supplierorderitem_supplierorder"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierorder",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="supplierorderitem",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_fulfillment",
                to="orders.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="supplierorderitem",
            name="supplier_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.supplierorder",
            ),
        ),
    ]
