# Generated by Django 5.0.14 on 2026-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("smart", "Smart (Automated Rules)")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="rules",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
