# Generated by Django 5.0.14 on 2026-08-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("is_published", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=150, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Aura", max_length=150)),
                (
                    "support_email",
                    models.EmailField(default="support@aura.com", max_length=254),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Percentage tax rate",
                        max_digits=5,
                    ),
                ),
                (
                    "flat_shipping_rate",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("featured_products", "Featured Products"),
                            ("text_image", "Text with Image"),
                            ("newsletter", "Newsletter Signup"),
                            ("custom_html", "Custom HTML"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="JSON payload containing section specific data (e.g., image_url, text, product_ids)",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
