# Generated by Django 5.0.14 on 2026-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_page_storesettings_pagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslider",
            name="enable_3d_effect",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="heroslider",
            name="secondary_cta_link",
            field=models.CharField(
                blank=True, default="/lookbook", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="heroslider",
            name="secondary_cta_text",
            field=models.CharField(
                blank=True, default="View Lookbook", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="heroslider",
            name="cta_text",
            field=models.CharField(default="Explore Collection", max_length=50),
        ),
        migrations.AlterField(
            model_name="heroslider",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
